/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import javax.swing.JPanel;

/**
 *
 * @author Sebi
 */
public class PanelTrack extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrack
     */
    public PanelTrack() {
        initComponents();
    }
    public JPanel getDrawPanel()
    {
        return pDraw;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDraw = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        pDraw.setBorder(javax.swing.BorderFactory.createTitledBorder("Draw Panel"));

        javax.swing.GroupLayout pDrawLayout = new javax.swing.GroupLayout(pDraw);
        pDraw.setLayout(pDrawLayout);
        pDrawLayout.setHorizontalGroup(
            pDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        pDrawLayout.setVerticalGroup(
            pDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        add(pDraw);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pDraw;
    // End of variables declaration//GEN-END:variables
}
